export interface CurrencyType {
  code: string;
  name: string;
  countryCode: string;
}

export const currencyList: CurrencyType[] = [
  { code: "USD", name: "US Dollar", countryCode: "us" },
  { code: "EUR", name: "Euro", countryCode: "eu" },
  { code: "GBP", name: "British Pound", countryCode: "gb" },
  { code: "INR", name: "Indian Rupee", countryCode: "in" },
  { code: "AED", name: "UAE Dirham", countryCode: "ae" },
  { code: "JPY", name: "Japanese Yen", countryCode: "jp" },
  { code: "AUD", name: "Australian Dollar", countryCode: "au" },
  { code: "CAD", name: "Canadian Dollar", countryCode: "ca" },
  { code: "CHF", name: "Swiss Franc", countryCode: "ch" },
  { code: "CNY", name: "Chinese Yuan", countryCode: "cn" },
  { code: "SGD", name: "Singapore Dollar", countryCode: "sg" },
  { code: "NZD", name: "New Zealand Dollar", countryCode: "nz" },
  { code: "HKD", name: "Hong Kong Dollar", countryCode: "hk" },
  { code: "KRW", name: "South Korean Won", countryCode: "kr" },
  { code: "THB", name: "Thai Baht", countryCode: "th" },
  { code: "MYR", name: "Malaysian Ringgit", countryCode: "my" },
  { code: "ZAR", name: "South African Rand", countryCode: "za" },
  { code: "BRL", name: "Brazilian Real", countryCode: "br" },
  { code: "RUB", name: "Russian Ruble", countryCode: "ru" },
  { code: "TRY", name: "Turkish Lira", countryCode: "tr" },
  { code: "SAR", name: "Saudi Riyal", countryCode: "sa" },
  { code: "QAR", name: "Qatari Riyal", countryCode: "qa" },
  { code: "KWD", name: "Kuwaiti Dinar", countryCode: "kw" },
  { code: "BHD", name: "Bahraini Dinar", countryCode: "bh" },
  { code: "OMR", name: "Omani Rial", countryCode: "om" },
  { code: "EGP", name: "Egyptian Pound", countryCode: "eg" },
  { code: "PKR", name: "Pakistani Rupee", countryCode: "pk" },
  { code: "BDT", name: "Bangladeshi Taka", countryCode: "bd" },
  { code: "LKR", name: "Sri Lankan Rupee", countryCode: "lk" },
  { code: "NPR", name: "Nepalese Rupee", countryCode: "np" },
  { code: "IDR", name: "Indonesian Rupiah", countryCode: "id" },
  { code: "PHP", name: "Philippine Peso", countryCode: "ph" },
  { code: "VND", name: "Vietnamese Dong", countryCode: "vn" },
  { code: "MXN", name: "Mexican Peso", countryCode: "mx" },
  { code: "ARS", name: "Argentine Peso", countryCode: "ar" },
  { code: "CLP", name: "Chilean Peso", countryCode: "cl" },
  { code: "COP", name: "Colombian Peso", countryCode: "co" },
  { code: "PLN", name: "Polish Zloty", countryCode: "pl" },
  { code: "SEK", name: "Swedish Krona", countryCode: "se" },
  { code: "NOK", name: "Norwegian Krone", countryCode: "no" },
  { code: "DKK", name: "Danish Krone", countryCode: "dk" },
  { code: "HUF", name: "Hungarian Forint", countryCode: "hu" },
  { code: "CZK", name: "Czech Koruna", countryCode: "cz" },
  { code: "RON", name: "Romanian Leu", countryCode: "ro" },
  { code: "ILS", name: "Israeli Shekel", countryCode: "il" },
  { code: "NGN", name: "Nigerian Naira", countryCode: "ng" },
  { code: "KES", name: "Kenyan Shilling", countryCode: "ke" },
  { code: "GHS", name: "Ghanaian Cedi", countryCode: "gh" },
  { code: "UAH", name: "Ukrainian Hryvnia", countryCode: "ua" },
  { code: "MAD", name: "Moroccan Dirham", countryCode: "ma" },
  { code: "TND", name: "Tunisian Dinar", countryCode: "tn" },
  { code: "DZD", name: "Algerian Dinar", countryCode: "dz" },
  { code: "ETB", name: "Ethiopian Birr", countryCode: "et" },
  { code: "XOF", name: "West African CFA Franc", countryCode: "sn" },
  { code: "XAF", name: "Central African CFA Franc", countryCode: "cm" },
];
