export interface CurrencyType {
  code: string;
  name: string;
  countryCode: string;
}

export const currencyList: CurrencyType[] = [
  { code: "USD", name: "US Dollar", countryCode: "us" },
  { code: "EUR", name: "Euro", countryCode: "eu" },
  { code: "GBP", name: "British Pound", countryCode: "gb" },
  { code: "INR", name: "Indian Rupee", countryCode: "in" },
  { code: "AED", name: "UAE Dirham", countryCode: "ae" },
  { code: "JPY", name: "Japanese Yen", countryCode: "jp" },
  { code: "AUD", name: "Australian Dollar", countryCode: "au" },
  { code: "CAD", name: "Canadian Dollar", countryCode: "ca" },
  { code: "CHF", name: "Swiss Franc", countryCode: "ch" },
  { code: "CNY", name: "Chinese Yuan", countryCode: "cn" },
  { code: "SGD", name: "Singapore Dollar", countryCode: "sg" },
  { code: "NZD", name: "New Zealand Dollar", countryCode: "nz" },
  { code: "HKD", name: "Hong Kong Dollar", countryCode: "hk" },
  { code: "KRW", name: "South Korean Won", countryCode: "kr" },
  { code: "THB", name: "Thai Baht", countryCode: "th" },
  { code: "MYR", name: "Malaysian Ringgit", countryCode: "my" },
  { code: "ZAR", name: "South African Rand", countryCode: "za" },
  { code: "BRL", name: "Brazilian Real", countryCode: "br" },
  { code: "RUB", name: "Russian Ruble", countryCode: "ru" },
  { code: "TRY", name: "Turkish Lira", countryCode: "tr" },
  { code: "SAR", name: "Saudi Riyal", countryCode: "sa" },
  { code: "QAR", name: "Qatari Riyal", countryCode: "qa" },
  { code: "KWD", name: "Kuwaiti Dinar", countryCode: "kw" },
  { code: "BHD", name: "Bahraini Dinar", countryCode: "bh" },
  { code: "OMR", name: "Omani Rial", countryCode: "om" },
  { code: "EGP", name: "Egyptian Pound", countryCode: "eg" },
  { code: "PKR", name: "Pakistani Rupee", countryCode: "pk" },
  { code: "BDT", name: "Bangladeshi Taka", countryCode: "bd" },
  { code: "LKR", name: "Sri Lankan Rupee", countryCode: "lk" },
  { code: "NPR", name: "Nepalese Rupee", countryCode: "np" },
  { code: "IDR", name: "Indonesian Rupiah", countryCode: "id" },
  { code: "PHP", name: "Philippine Peso", countryCode: "ph" },
  { code: "VND", name: "Vietnamese Dong", countryCode: "vn" },
  { code: "MXN", name: "Mexican Peso", countryCode: "mx" },
  { code: "ARS", name: "Argentine Peso", countryCode: "ar" },
  { code: "CLP", name: "Chilean Peso", countryCode: "cl" },
  { code: "COP", name: "Colombian Peso", countryCode: "co" },
  { code: "PLN", name: "Polish Zloty", countryCode: "pl" },
  { code: "SEK", name: "Swedish Krona", countryCode: "se" },
  { code: "NOK", name: "Norwegian Krone", countryCode: "no" },
  { code: "DKK", name: "Danish Krone", countryCode: "dk" },
  { code: "HUF", name: "Hungarian Forint", countryCode: "hu" },
  { code: "CZK", name: "Czech Koruna", countryCode: "cz" },
  { code: "RON", name: "Romanian Leu", countryCode: "ro" },
  { code: "ILS", name: "Israeli Shekel", countryCode: "il" },
  { code: "NGN", name: "Nigerian Naira", countryCode: "ng" },
  { code: "KES", name: "Kenyan Shilling", countryCode: "ke" },
  { code: "GHS", name: "Ghanaian Cedi", countryCode: "gh" },
  { code: "UAH", name: "Ukrainian Hryvnia", countryCode: "ua" },
  { code: "MAD", name: "Moroccan Dirham", countryCode: "ma" },
  { code: "TND", name: "Tunisian Dinar", countryCode: "tn" },
  { code: "DZD", name: "Algerian Dinar", countryCode: "dz" },
  { code: "ETB", name: "Ethiopian Birr", countryCode: "et" },
  { code: "XOF", name: "West African CFA Franc", countryCode: "sn" },
  { code: "XAF", name: "Central African CFA Franc", countryCode: "cm" },
  { code: "AFN", name: "Afghan Afghani", countryCode: "af" },
  { code: "ALL", name: "Albanian Lek", countryCode: "al" },
  { code: "AMD", name: "Armenian Dram", countryCode: "am" },
  { code: "AOA", name: "Angolan Kwanza", countryCode: "ao" },
  { code: "AZN", name: "Azerbaijani Manat", countryCode: "az" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", countryCode: "ba" },
  { code: "BBD", name: "Barbadian Dollar", countryCode: "bb" },
  { code: "BND", name: "Brunei Dollar", countryCode: "bn" },
  { code: "BOB", name: "Bolivian Boliviano", countryCode: "bo" },
  { code: "BSD", name: "Bahamian Dollar", countryCode: "bs" },
  { code: "BWP", name: "Botswana Pula", countryCode: "bw" },
  { code: "BYN", name: "Belarusian Ruble", countryCode: "by" },
  { code: "CRC", name: "Costa Rican Colon", countryCode: "cr" },
  { code: "CUP", name: "Cuban Peso", countryCode: "cu" },
  { code: "DJF", name: "Djiboutian Franc", countryCode: "dj" },
  { code: "DOP", name: "Dominican Peso", countryCode: "do" },
  { code: "FJD", name: "Fijian Dollar", countryCode: "fj" },
  { code: "GEL", name: "Georgian Lari", countryCode: "ge" },
  { code: "GTQ", name: "Guatemalan Quetzal", countryCode: "gt" },
  { code: "HNL", name: "Honduran Lempira", countryCode: "hn" },
  { code: "HTG", name: "Haitian Gourde", countryCode: "ht" },
  { code: "ISK", name: "Icelandic Krona", countryCode: "is" },
  { code: "JMD", name: "Jamaican Dollar", countryCode: "jm" },
  { code: "JOD", name: "Jordanian Dinar", countryCode: "jo" },
  { code: "KZT", name: "Kazakhstani Tenge", countryCode: "kz" },
  { code: "LAK", name: "Lao Kip", countryCode: "la" },
  { code: "LBP", name: "Lebanese Pound", countryCode: "lb" },
  { code: "MGA", name: "Malagasy Ariary", countryCode: "mg" },
  { code: "MKD", name: "Macedonian Denar", countryCode: "mk" },
  { code: "MNT", name: "Mongolian Tugrik", countryCode: "mn" },
  { code: "MOP", name: "Macanese Pataca", countryCode: "mo" },
  { code: "MUR", name: "Mauritian Rupee", countryCode: "mu" },
  { code: "MVR", name: "Maldivian Rufiyaa", countryCode: "mv" },
  { code: "NAD", name: "Namibian Dollar", countryCode: "na" },
  { code: "PAB", name: "Panamanian Balboa", countryCode: "pa" },
  { code: "PEN", name: "Peruvian Sol", countryCode: "pe" },
  { code: "PYG", name: "Paraguayan Guarani", countryCode: "py" },
  { code: "RSD", name: "Serbian Dinar", countryCode: "rs" },
  { code: "SLL", name: "Sierra Leonean Leone", countryCode: "sl" },
  { code: "SOS", name: "Somali Shilling", countryCode: "so" },
  { code: "SRD", name: "Surinamese Dollar", countryCode: "sr" },
  { code: "SYP", name: "Syrian Pound", countryCode: "sy" },
  { code: "TJS", name: "Tajikistani Somoni", countryCode: "tj" },
  { code: "TMT", name: "Turkmenistani Manat", countryCode: "tm" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", countryCode: "tt" },
  { code: "UYU", name: "Uruguayan Peso", countryCode: "uy" },
  { code: "UZS", name: "Uzbekistani Som", countryCode: "uz" },
  { code: "YER", name: "Yemeni Rial", countryCode: "ye" },
  { code: "ZMW", name: "Zambian Kwacha", countryCode: "zm" },
];
